### PR TITLE
getting version changes in

### PR DESCRIPTION
**Pull request by puja108**
WIP

### CODE REVIEW

**Comment by rsokolkov** [comment]
@puja108 can you please use master_use_external_kubeconfig branch

**Comment by puja108** [comment]
ah, good to know

**Comment by rsokolkov** [comment]
WIP ? I see only hard-coded version

**Comment by puja108** [comment]
Should be done now incl env for version, just updating to latest stable in Dockerfile and testing again.

**Comment by puja108** [comment]
all done RFR @rsokolkov (feel free to fix ugly bash 😉 )

**Comment by rsokolkov** [comment]
thanks, i'll check tonight

**Comment by rsokolkov** [comment]
LGTM

**Pull request merged**
